apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    name: postgresdb-service
    type: postgres-service
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-app
    name: postgres-pod
