apiVersion: v1
kind: Pod
metadata:
  name: result-pod
  labels:
   app: result-app
   name: result-pod
spec:
  containers:
  - name: result-container
    image: datagridsys/sample-result
    ports:
    - containerPort: 80
