apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    app: resultservice-app
    name: result-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: result-app
    name: result-pod