apiVersion: v1
kind: Pod
metadata:
  name: voting-pod
  labels:
    app: voting-app
    name: voting-pod
spec:
  containers:
  - name: voting-container
    image: dockersamples/examplevotingapp_vote
    ports:
    - containerPort: 80