apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    app: votingservice-app
    name: voting-app-service
specs:
  type: LoadBalancer
  ports:
  - ports: 80
    targetport: 80
  selector:
    app: voting-app
    name: voting-pod