apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
   app: worker-app
   name: worker-pod
spec:
  containers:
  - name: worker-container
    image: dockersamples/examplevotingapp_worker
